plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.mazeoffear.game'
    compileSdk 36

    defaultConfig {
        applicationId "com.mazeoffear.game"
        minSdk 24
        targetSdk 36
        versionCode 6
        versionName "1.0.0.6"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file('mazeoffear-release-key.jks')
            storePassword 'WMC7zYWdoL4w'
            keyAlias 'my-key-alias'
            keyPassword 'WMC7zYWdoL4w'
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    
    // Google AdMob Native SDK
    implementation 'com.google.android.gms:play-services-ads:23.0.0'
}
